---
title: "Homework week 7 day 1"
output: 
  html_document:
    code_folding: hide
---

```{r}
library(lubridate)
library(tibble)
library(tidyverse)
library(tsibble)
library(tsibbledata)
library(slider)
```


```{r}
# Add derived columns to dataset

nyc_bikes_df <- nyc_bikes %>% 
  mutate(
    start_date = as_date(start_time),
    stop_date = as_date(stop_time),
    start_year = year(start_time),
    start_quarter = quarter(start_time),
    start_month = month(start_time,
                        label = TRUE,
                        abbr = FALSE),
    start_weekday = wday(start_time,
                    week_start = 1,
                    label = TRUE,
                    abbr = FALSE),
    start_hour = hour(start_time),
    start_minute = minute(start_time),
    start_hour_numeric = (start_hour + (start_minute/60)),
    trip_duration = (stop_time - start_time),
    age = start_year - birth_year,
    age_group = case_when(age  >= 65 ~ "65+",
                          age  >= 55 ~ "55 - 64",
                          age  >= 45 ~ "45 - 54",
                          age  >= 35 ~ "35 - 44",
                          age  >= 25 ~ "25 - 34",
                          age  >= 18 ~ "18 - 24",
                          TRUE ~ NA_character_
    )
  )
```

### Checks: age
```{r}
nyc_bikes_df %>% 
filter(age >= 130 | age <= 18) %>% 
  select(age, birth_year)
```
### Checks :  hires longer than one day

```{r}
nyc_bikes_df %>% 
  filter(start_date != stop_date) %>% 
  select(hire_duration,
         start_time,
         stop_time) %>% 
  arrange(desc(hire_duration))
```
### Checks :  longest/shortest hires

```{r}
nyc_bikes_df %>% 
  select(hire_duration,
         start_date,
         stop_date) %>% 
  arrange(desc(hire_duration)) %>% 
  head(20)

nyc_bikes_df %>% 
  select(hire_duration,
         start_date,
         stop_date) %>% 
  arrange(hire_duration) %>% 
  head(20)
```

### Checks :  days with most hires
```{r}
nyc_bikes_df %>%
  index_by(start_date) %>% 
  summarise(number_of_hires = n()) %>% 
  arrange(desc(number_of_hires)) %>% 
  head(50)
```



```{r}
nyc_bikes_df %>% 
index_by(start_weekday) %>% 
group_by(gender) %>% 
summarise(number_of_hires = n()) %>% 
ggplot() +
  aes(x = start_weekday, y = number_of_hires) +
  geom_col()
```


```{r}
nyc_bikes_df %>%
  filter(gender!= "Unknown") %>% 
  index_by(start_date) %>%
  group_by(gender) %>% 
  summarise(number_of_hires = n()) %>% 
ggplot() +
  aes(x = start_date, y = number_of_hires) +
  geom_line() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~gender)
    
```

```{r}
nyc_bikes_df %>%
  filter(gender!= "Unknown") %>% 
  index_by(start_month) %>%
  group_by(gender) %>% 
  summarise(number_of_hires = n()) %>% 
ggplot() +
  aes(x = start_month, y = number_of_hires) +
  geom_col(fill = "steel blue") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~gender)
```

```{r}
nyc_bikes_df %>%
  filter(age < 130) %>% 
  index_by(start_hour_numeric) %>%
  group_by(gender) %>% 
  summarise(number_of_hires = n()) %>% 
ggplot() +
  aes(x = start_hour_numeric, y = number_of_hires) +
  geom_col(fill = "steel blue") +
  theme_minimal() 
```


```{r}
nyc_bikes_df %>% 
select(stop_time, start_time) %>% 
  mutate(hire_t = stop_time - start_time)
```

```{r}
test <- tibble(nyc_bikes_df %>% 
  group_by(start_station, start_lat, start_long) %>% 
  summarise(count = n())
)
test <- test %>% 
  group_by(start_station, start_lat, start_long) %>% 
  summarise(count = sum(count)) %>% 
arrange(desc(count))


```


```{r}
# source data for trips by time of day
nyc_bikes_df %>%
  index_by(start_hour_numeric) %>%
  group_by(age_group) %>% 
  summarise(number_of_trips = n()) %>% 
  mutate(
    trips_moving_average = slide_dbl(
      number_of_trips,
      ~ mean(., na.rm = TRUE),
      .before = 75,
      .after = 75,
      .complete = FALSE
    )
  ) %>% 
ggplot() +
  aes(x = start_hour_numeric, y = number_of_trips) +
  geom_line(colour = "light grey") +
  geom_line(aes(y = trips_moving_average), colour = "red") +
  scale_x_continuous(breaks = c(3, 6, 9, 12, 15, 18, 21, 24)) +
  scale_y_continuous(breaks = c(2, 4, 6, 8)) +
  theme_minimal() +
  labs(
    title = "Number of trips by time of day \n",
    x = "\n Time (24h)",
    y = "Number of trips \n"
  ) +
  facet_wrap(~age_group)
```

